return {
	Daily = {
		{
			Name = "Silence the Mud Scouts",
			Description = "Mud Scouts are crawling too close to our trenches. Send 5 of them back underground.",
			TargetDataName = "Kills.Mud Scout",
			TargetAmount = 5,
			Rewards = { Cash = 250 },
			XP = 100,
		},
		{
			Name = "Frontline Grunt Cleanup",
			Description = "Trench Grunts are forming a push. Defeat 5 before they turn the battlefield into Swiss cheese.",
			TargetDataName = "Kills.Trench Grunt",
			TargetAmount = 5,
			Rewards = { Cash = 250 },
			XP = 100,
		},
		{
			Name = "Crack the Bunker Bruisers",
			Description = "Bunker Bruisers are blocking the advance. Take down 2 of these oversized troublemakers.",
			TargetDataName = "Kills.Bunker Bruiser",
			TargetAmount = 2,
			Rewards = { Cash = 300 },
			XP = 120,
		},
		{
			Name = "Defuse the Walking Disaster",
			Description = "A Walking Dynamite unit has entered the field. Remove it before the whole operation goes boom.",
			TargetDataName = "Kills.Walking Dynamite",
			TargetAmount = 1,
			Rewards = { Cash = 300 },
			XP = 120,
		},
		{
			Name = "Operation Commander Boom",
			Description = "Commander Boom is leading the enemy squad. Defeat him and make the bunker cheer.",
			TargetDataName = "Kills.Commander Boom",
			TargetAmount = 1,
			Rewards = { Cash = 500 },
			XP = 150,
		},
		{
			Name = "Field Promotion",
			Description = "Upgrade any tower once and prove this bunker has more than rusty bolts.",
			TargetDataName = "TowerUpgrades",
			TargetAmount = 1,
			Rewards = { Cash = 300 },
			XP = 100,
		},
		{
			Name = "First Victory Salute",
			Description = "Win one round and give the enemy worms something to complain about.",
			TargetDataName = "Wins",
			TargetAmount = 1,
			Rewards = { Cash = 400 },
			XP = 150,
		},
		{
			Name = "Cash Crate Raid",
			Description = "Earn 2,000 cash in a single round. Command says shiny rewards improve morale.",
			TargetDataName = "CashGained",
			TargetAmount = 2000,
			Rewards = { Cash = 200 },
			XP = 80,
		},
		{
			Name = "Pocket Money Platoon",
			Description = "Earn 500 cash in a single round and keep the war machine mildly funded.",
			TargetDataName = "CashGained",
			TargetAmount = 500,
			Rewards = { Cash = 100 },
			XP = 50,
		},
	},

	Weekly = {
		{
			Name = "Mud Scout Hunt Patrol",
			Description = "Mud Scouts are mapping our defenses. Eliminate 15 before they report back to their mud hole.",
			TargetDataName = "Kills.Mud Scout",
			TargetAmount = 15,
			Rewards = { Cash = 800 },
			XP = 300,
		},
		{
			Name = "Break the Trench Line",
			Description = "The enemy grunts are digging in. Defeat 20 Trench Grunts and ruin their battle plan.",
			TargetDataName = "Kills.Trench Grunt",
			TargetAmount = 20,
			Rewards = { Cash = 900 },
			XP = 350,
		},
		{
			Name = "Bunker Bruiser Demolition",
			Description = "The Bunker Bruisers are stomping through the battlefield like they own it. Bring down 5 of them.",
			TargetDataName = "Kills.Bunker Bruiser",
			TargetAmount = 5,
			Rewards = { Cash = 1000 },
			XP = 400,
		},
		{
			Name = "Boom Squad Suppression",
			Description = "Walking Dynamites are turning every step into a health hazard. Defeat 10 before the map needs rebuilding.",
			TargetDataName = "Kills.Walking Dynamite",
			TargetAmount = 10,
			Rewards = { Cash = 1000 },
			XP = 400,
		},
		{
			Name = "Commander Boom Manhunt",
			Description = "Enemy commanders are crawling out of their bunkers. Defeat 5 Commander Booms and cut off their orders.",
			TargetDataName = "Kills.Commander Boom",
			TargetAmount = 5,
			Rewards = { Cash = 1200 },
			XP = 500,
		},
		{
			Name = "Bunker Engineer Duty",
			Description = "Upgrade any tower 5 times. A better tower means fewer worms yelling for backup.",
			TargetDataName = "TowerUpgrades",
			TargetAmount = 5,
			Rewards = { Cash = 800 },
			XP = 250,
		},
		{
			Name = "Five-Round Campaign",
			Description = "Win 5 rounds and prove your squad can survive more than one lucky explosion.",
			TargetDataName = "Wins",
			TargetAmount = 5,
			Rewards = { Cash = 1500 },
			XP = 600,
		},
		{
			Name = "War Chest Collector",
			Description = "Earn 10,000 cash in a single round. The bunker accountant is watching with great interest.",
			TargetDataName = "CashGained",
			TargetAmount = 10000,
			Rewards = { Cash = 1000 },
			XP = 350,
		},
		{
			Name = "Supply Line Shake-Up",
			Description = "Earn 5,000 cash in a single round and keep the crates rolling into base.",
			TargetDataName = "CashGained",
			TargetAmount = 5000,
			Rewards = { Cash = 600 },
			XP = 250,
		},
	},

	Monthly = {
		{
			Name = "The Great Mud Scout Sweep",
			Description = "The battlefield is crawling with Mud Scouts. Defeat 70 and make the trenches safe again.",
			TargetDataName = "Kills.Mud Scout",
			TargetAmount = 70,
			Rewards = { Cash = 2500 },
			XP = 1000,
		},
		{
			Name = "Trench Grunt Offensive",
			Description = "Trench Grunts are launching a full campaign. Defeat 65 and send their formation into chaos.",
			TargetDataName = "Kills.Trench Grunt",
			TargetAmount = 65,
			Rewards = { Cash = 2500 },
			XP = 1000,
		},
		{
			Name = "Heavy Bunker War",
			Description = "The Bunker Bruisers are trying to crush the front line. Defeat 45 and turn their armor into scrap.",
			TargetDataName = "Kills.Bunker Bruiser",
			TargetAmount = 45,
			Rewards = { Cash = 3000 },
			XP = 1200,
		},
		{
			Name = "Dynamite Threat Neutralized",
			Description = "Walking Dynamites have taken over the field. Defeat 25 before the entire island learns to fly.",
			TargetDataName = "Kills.Walking Dynamite",
			TargetAmount = 25,
			Rewards = { Cash = 3000 },
			XP = 1200,
		},
		{
			Name = "Command Bunker Takedown",
			Description = "Commander Boom is leading the enemy war effort. Defeat 15 and leave their command room full of panic.",
			TargetDataName = "Kills.Commander Boom",
			TargetAmount = 15,
			Rewards = { Cash = 4000 },
			XP = 1500,
		},
		{
			Name = "Master Bunker Engineer",
			Description = "Upgrade any tower 20 times and transform your defenses from scrap metal into worm-stopping machinery.",
			TargetDataName = "TowerUpgrades",
			TargetAmount = 20,
			Rewards = { Cash = 2500 },
			XP = 900,
		},
		{
			Name = "Twenty Battles, One Squad",
			Description = "Win 20 rounds and earn your place among the most stubborn worms on the battlefield.",
			TargetDataName = "Wins",
			TargetAmount = 20,
			Rewards = { Cash = 5000 },
			XP = 2000,
		},
		{
			Name = "Crate Baron Campaign",
			Description = "Earn 45,000 cash in a single round. At this point, even the enemy wants to know your budget.",
			TargetDataName = "CashGained",
			TargetAmount = 45000,
			Rewards = { Cash = 3000 },
			XP = 1000,
		},
		{
			Name = "Bunker Treasury Raid",
			Description = "Earn 25,000 cash in a single round and prove your squad knows how to fight and profit.",
			TargetDataName = "CashGained",
			TargetAmount = 25000,
			Rewards = { Cash = 2000 },
			XP = 800,
		},
	}
}